#!/usr/bin/python3

import sys
import uuid

def main(roothash: str):
    roothash = roothash.ljust(64, '0')

    root_uuid = roothash[0:32]
    verity_uuid = roothash[32:64]

    print(
        uuid.UUID(hex=root_uuid),
        uuid.UUID(hex=verity_uuid),
    )

main(sys.argv[1])
